version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=12345
    ports:
      - 80:80
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12345
    ports:
      - 5432:5432

